server:
  servlet:
    context-path: /data-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///data
    username: postgres
    password: password
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: sep4-386306:europe-west3:sep4

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

